### ISSUE TITLE
[BUG] add total_precip to multiformer 

### ISSUE THREAD

**Issue by iluise** [clessig/atmorep#55]
**Describe the bug**
When adding `total_precip` as additional field in the multiformer (with embedding dim 1536 as for the paper) I get errors at random times (it varies and it is not always at the same epoch). It seems to train correctly as the loss decreases as expected, but I get the following errors after a while: 

The first time I got this at **epoch: 2 [99/512 (19%)]**   

`````
[rank7]:[E ProcessGroupNCCL.cpp:1414] [PG 0 Rank 7] Process group watchdog thread terminated with exception: CUDA erro
r: unspecified launch failure
7: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect
.
7: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
7: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
7: 
7: Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
7: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fe9e4f77897 in /gpfs/home/cern/cern890661/atm
orep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10.so)
7: frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7fe9e4f27b
25 in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10.so)
7: frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7fe9e504f718 i
n /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10_cuda.so)
7: frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7fe9e624de36 in /gpfs/home/
cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
7: frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x58 (0x7fe9e6251f38 in /gpfs/home/cern/cern890661/atmorep
/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
7: frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x77c (0x7fe9e62575ac in /gpfs/home/cern/cern890661/atmorep/atmo
rep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
7: frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7fe9e625831c in /gpfs/home/cern/cern890661/atmorep/atm
orep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
7: frame #7: <unknown function> + 0xdb9d4 (0x7fea31d179d4 in /lib64/libstdc++.so.6)
7: frame #8: <unknown function> + 0x9f802 (0x7fea40628802 in /lib64/libc.so.6)
7: frame #9: <unknown function> + 0x3f450 (0x7fea405c8450 in /lib64/libc.so.6)
7: 
7: terminate called after throwing an instance of 'c10::DistBackendError'
7:   what():  [PG 0 Rank 7] Process group watchdog thread terminated with exception: CUDA error: unspecified launch failu
re
7: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect
.
7: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
7: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
7: 
7: Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
7: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fe9e4f77897 in /gpfs/home/cern/cern890661/atm
orep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10.so)
7: frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7fe9e4f27b
25 in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10.so)
7: frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7fe9e504f718 i
n /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10_cuda.so)
7: frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7fe9e624de36 in /gpfs/home/
cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
7: frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x58 (0x7fe9e6251f38 in /gpfs/home/cern/cern890661/atmorep
/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
7: frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x77c (0x7fe9e62575ac in /gpfs/home/cern/cern890661/atmorep/atmo
rep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
7: frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7fe9e625831c in /gpfs/home/cern/cern890661/atmorep/atm
orep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
7: frame #7: <unknown function> + 0xdb9d4 (0x7fea31d179d4 in /lib64/libstdc++.so.6)
7: frame #8: <unknown function> + 0x9f802 (0x7fea40628802 in /lib64/libc.so.6)
7: frame #9: <unknown function> + 0x3f450 (0x7fea405c8450 in /lib64/libc.so.6)
7: 
7: Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1418 (most recent call f
irst):
7: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fe9e4f77897 in /gpfs/home/cern/cern890661/atm
orep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10.so)
7: frame #1: <unknown function> + 0xe32e33 (0x7fe9e5edae33 in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib6
4/python3.9/site-packages/torch/lib/libtorch_cuda.so)
7: frame #2: <unknown function> + 0xdb9d4 (0x7fea31d179d4 in /lib64/libstdc++.so.6)
7: frame #3: <unknown function> + 0x9f802 (0x7fea40628802 in /lib64/libc.so.6)
3: [rank3]: Traceback (most recent call last):
3: [rank3]:   File "/usr/lib64/python3.9/multiprocessing/resource_sharer.py", line 138, in _serve
3: [rank3]:     with self._listener.accept() as conn:
3: [rank3]:   File "/usr/lib64/python3.9/multiprocessing/connection.py", line 470, in accept
3: [rank3]:     answer_challenge(c, self._authkey)
3: [rank3]:   File "/usr/lib64/python3.9/multiprocessing/connection.py", line 761, in answer_challenge
3: [rank3]:     response = connection.recv_bytes(256)        # reject large message
3: [rank3]:   File "/usr/lib64/python3.9/multiprocessing/connection.py", line 220, in recv_bytes
3: [rank3]:     buf = self._recv_bytes(maxlength)
3: [rank3]:   File "/usr/lib64/python3.9/multiprocessing/connection.py", line 418, in _recv_bytes
3: [rank3]:     buf = self._recv(4)
3: [rank3]:   File "/usr/lib64/python3.9/multiprocessing/connection.py", line 383, in _recv
3: [rank3]:     chunk = read(handle, remaining)
3: [rank3]: ConnectionResetError: [Errno 104] Connection reset by peer

``````

retrying from scratch with the exact same code I got this at **epoch: 1 [29/512 (6%)]**   : 

``````
6: [rank6]:[F ProcessGroupNCCL.cpp:1169] [PG 0 Rank 6] [PG 0 Rank 6] ProcessGroupNCCL's watchdog got stuck for 600 second
s without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API hang blocking the 
watchdog, and could be triggered by another thread holding the GIL inside a CUDA api, or other deadlock-prone behaviors.I
f you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TO
RCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If ei
ther of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; othe
rwise, please attempt to debug the hang. workMetaList_.size() = 42
srun: error: as06r5b28: task 6: Aborted
srun: Terminating StepId=10840010.0
``````

when using the same embedding dimension as the other fields I got  the error at **epoch: 5 [59/512 (12%)]**:

``````
[rank0]:[E ProcessGroupNCCL.cpp:1414] [PG 0 Rank 0] Process group watchdog thread terminated with exception: CUDA erro
r: unspecified launch failure
0: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect
.
0: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
0: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
0: 
0: Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
0: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7ffa085d3897 in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10.so)
0: frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7ffa08583b25 in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10.so)
0: frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7ffa086ab718 in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10_cuda.so)
0: frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7ffa098a9e36 in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
0: frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x58 (0x7ffa098adf38 in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
0: frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x77c (0x7ffa098b35ac in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
0: frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7ffa098b431c in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
0: frame #7: <unknown function> + 0xdb9d4 (0x7ffa553739d4 in /lib64/libstdc++.so.6)
0: frame #8: <unknown function> + 0x9f802 (0x7ffa63c84802 in /lib64/libc.so.6)
0: frame #9: <unknown function> + 0x3f450 (0x7ffa63c24450 in /lib64/libc.so.6)
0: 
0: terminate called after throwing an instance of 'c10::DistBackendError'
0:   what():  [PG 0 Rank 0] Process group watchdog thread terminated with exception: CUDA error: unspecified launch failure
0: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
0: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
0: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
0: 
0: Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
0: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7ffa085d3897 in /gpfs/home/cern/cern890661/atm
orep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10.so)
0: frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7ffa08583b
25 in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10.so)
0: frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7ffa086ab718 i
n /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10_cuda.so)
0: frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7ffa098a9e36 in /gpfs/home/
cern/cern890661/atmorep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
0: frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x58 (0x7ffa098adf38 in /gpfs/home/cern/cern890661/atmorep
/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
0: frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x77c (0x7ffa098b35ac in /gpfs/home/cern/cern890661/atmorep/atmo
rep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
0: frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7ffa098b431c in /gpfs/home/cern/cern890661/atmorep/atm
orep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libtorch_cuda.so)
0: frame #7: <unknown function> + 0xdb9d4 (0x7ffa553739d4 in /lib64/libstdc++.so.6)
0: frame #8: <unknown function> + 0x9f802 (0x7ffa63c84802 in /lib64/libc.so.6)
0: frame #9: <unknown function> + 0x3f450 (0x7ffa63c24450 in /lib64/libc.so.6)
0: 
0: Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1418 (most recent call f
irst):
0: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7ffa085d3897 in /gpfs/home/cern/cern890661/atm
orep/atmorep_May24/pyenv/lib64/python3.9/site-packages/torch/lib/libc10.so)
0: frame #1: <unknown function> + 0xe32e33 (0x7ffa09536e33 in /gpfs/home/cern/cern890661/atmorep/atmorep_May24/pyenv/lib6
4/python3.9/site-packages/torch/lib/libtorch_cuda.so)
0: frame #2: <unknown function> + 0xdb9d4 (0x7ffa553739d4 in /lib64/libstdc++.so.6)
0: frame #3: <unknown function> + 0x9f802 (0x7ffa63c84802 in /lib64/libc.so.6)
0: frame #4: <unknown function> + 0x3f450 (0x7ffa63c24450 in /lib64/libc.so.6)
``````

**To Reproduce**
1.  checkout `iluise/head`
2. uncomment this line https://github.com/clessig/atmorep/blob/iluise/head/atmorep/core/train_multi.py#L144 and remove the  `['3kdutwqb', 900]]` bracket. 
3. uncomment this line https://github.com/clessig/atmorep/blob/iluise/head/atmorep/core/train_multi.py#L152
4. Run train_multi.py
5. See error

**Hardware and environment:**
 - System: BSC
 - Runtime: sbatch
 - Special branch: iluise/head 
 - Python Version: 3.9, torch 2.3

**Additional context**
Without total_precip the code runs smoothly. 

tagging @mlangguth89 so you can track the progress. I can take a look at the run that stopped at epoch 5 and copy it to JSC for the downscaling pipeline while we debug this problem if you want.

**Comment by clessig** [comment]
Can you run it with CUDA_LAUNCH_BLOCKING=1. This should give a better stack trace.

**Comment by mlangguth89** [comment]
Also tag @ankitpatnala so that he is kept updated as well!

**Comment by iluise** [comment]
Th error has actually disappeared. Closing the issue for now. I am copying a 72h trained multiformer including total precip to JSC. I checked it really quickly, and I hand over to you the full validation.
