### ISSUE TITLE
[BUG] RuntimeError: No available kernel. Aborting execution.

### ISSUE THREAD

**Issue by maruf-anu** [clessig/atmorep#75]
I recently installed Atmorep in a conda env with Pytorch 2.4 and cuda 12.1. 
However, the code doesn't run, has the following error
```
RuntimeError: No available kernel. Aborting execution.
```
Anyone having a working conda/pip env, can you please list the packages?

**Comment by maruf-anu** [comment]
```
Traceback (most recent call last):
  File "/scratch/atmorep_2024/atmorep/core/evaluate.py", line 77, in <module>
    Evaluator.evaluate( mode, model_id, file_path, options)
  File "/scratch/atmorep_2024/atmorep/core/evaluator.py", line 115, in evaluate
    func( cf, model_id, model_epoch, devices, args)
  File "/scratch/atmorep_2024/atmorep/core/evaluator.py", line 174, in global_forecast
    evaluator.validate( 0, cf.BERT_strategy)
  File "/scratch/atmorep_2024/atmorep/core/trainer.py", line 380, in validate
    preds, atts = self.model( batch_data)
  File "/scratch/env/atmorep/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/env/atmorep/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/atmorep_2024/atmorep/core/atmorep_model.py", line 168, in forward
    pred = self.net.forward( xin)
  File "/scratch/atmorep_2024/atmorep/core/atmorep_model.py", line 519, in forward
    fields_embed, att = self.forward_encoder_block( ib, fields_embed)
  File "/scratch/atmorep_2024/atmorep/core/atmorep_model.py", line 553, in forward_encoder_block
    y, att = self.checkpoint( self.encoders[ifield].heads[iblock], *fields_in)
  File "/scratch/atmorep_2024/atmorep/transformer/transformer_base.py", line 26, in checkpoint_wrapper
    return cmodule(*kwargs)
  File "/scratch/env/atmorep/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/env/atmorep/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/fp0/mah900atmorep_2024/atmorep/transformer/transformer_attention.py", line 256, in forward
    outs = self.att( qs, ks, vs).transpose( -3, -2).flatten( -2, -1).reshape(s)
RuntimeError: No available kernel. Aborting execution.
```

**Comment by clessig** [comment]
The error sounds like a torch problem but if you 2.4 then it should work. Here's a requirements.txt from my env:

[requirements.txt](https://github.com/user-attachments/files/18122923/requirements.txt)

**Comment by maruf-anu** [comment]
The packages list works, thanks very much.
However, PyTest is causing a caching error

```
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.10.16, pytest-8.3.4, pluggy-1.5.0 -- /scratch/env/atmorep/bin/python
cachedir: .pytest_cache
rootdir: /scratch/atmorep_2024
plugins: anyio-4.7.0
collected 0 items                                                                                                                                                                              

======================================================================================= warnings summary =======================================================================================
../../../env/atmorep/lib/python3.10/site-packages/_pytest/config/__init__.py:1277
  /scratch/env/atmorep/lib/python3.10/site-packages/_pytest/config/__init__.py:1277: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: anyio
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================================== 1 warning in 0.06s ======================================================================================
```
This is due to multiple `pytest.main()` call from the same process. 
Is the PyTest strictly necessary? or can be ignored.

**Comment by iluise** [comment]
Hi, no it's not critical. you can set 'with_pytest' : False and it should skip it. This will be soon refactored in a separate testing pipeline so it's just a temporary solution.
