### ISSUE TITLE
[BUG] Unable to load weights of embeds_token_info module of the pre-trained model in the case of multiformer

### ISSUE THREAD

**Issue by ankitpatnala** [clessig/atmorep#78]
**Describe the bug**
https://github.com/clessig/atmorep/blob/3efcb122842b7cd285cb3074f84b98ef9665a306/atmorep/core/atmorep_model.py#L234-L259

Whenever my loading weights from a pre-trained multiformer model, the loading of weights fail
**To Reproduce**
1. Activate '...'
2. Change '....'
3. Run : Whenever model.create function is used i.e. with cf.fields for each variable containing the model_id in fields[1][4][0] variable 
```
0:   mloaded = torch.load( get_model_filename( name, field_info[1][4][0], field_info[1][4][1]))
0: Traceback (most recent call last):
0:   File "/p/project1/deepacf/atmo-rep/patnala1/atmorep/atmorep_downscaling_train_10699250/train.py", line 215, in <module>
0:     train()
0:   File "/p/project1/deepacf/atmo-rep/patnala1/atmorep/atmorep_downscaling_train_10699250/train.py", line 208, in train
0:     trainer = Trainer_Downscaling( cf, device).create()
0:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0:   File "/p/project1/deepacf/atmo-rep/patnala1/atmorep/atmorep/applications/downscaling/trainer.py", line 61, in create
0:     self.model.create( self.devices)
0:   File "/p/project1/deepacf/atmo-rep/patnala1/atmorep/atmorep/applications/downscaling/atmorep_downscaling.py", line 81, in create
0:     self.net = self.net.create( devices, load_pretrained)
0:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0:   File "/p/project1/deepacf/atmo-rep/patnala1/atmorep/atmorep/applications/downscaling/atmorep_downscaling.py", line 153, in create
0:     self.backbone = AtmoRep(cf).create(devices, load_pretrained=load_pretrained)
0:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0:   File "/p/project1/deepacf/atmo-rep/patnala1/atmorep/atmorep/core/atmorep_model.py", line 254, in create
0:     self.embeds_token_info[-1].load_state_dict( mloaded)
0:   File "/p/project/deepacf/atmo-rep/patnala1/atmorep/jsc_scripts/virtual_envs/venv_jwb/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
0:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
0: RuntimeError: Error(s) in loading state_dict for Linear:
0: 	Unexpected key(s) in state_dict: "1.weight", "1.bias", "2.weight", "2.bias", "3.weight", "3.bias", "4.weight", "4.bias", "5.weight", "5.bias". 
0: [rank0]:[W1218 15:56:07.722048163 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
```
**Expected behavior**
It should load pretrained weights of embeds_token_info corresponding to all the fields ( 6 in this case) 

**Screenshots/Explanations**
if you see line 249 and line 250, 
https://github.com/clessig/atmorep/blob/3efcb122842b7cd285cb3074f84b98ef9665a306/atmorep/core/atmorep_model.py#L249-L250
'0' is being used which refers to first field only. 
https://github.com/clessig/atmorep/blob/3efcb122842b7cd285cb3074f84b98ef9665a306/atmorep/core/atmorep_model.py#L251-L252
Once it is deleted, it is not able to find again.
The current code will only work if fieldinfo[0][1][4][0] contains model_id of singleformer. 

**Hardware and environment:**
 - System: JSC
 - Runtime: sbatch
 - Special branch: branch corresponds to  issue#76 ankitpatnala/ankit_downscaling/issue_076-feature-development-of-perceiver-model-for-downscaling
 -  Python Version: [e.g. 3.11]

**Additional context**
We do not need multiple embed_token_info for each field as token_infos are defined independently of field variable.

**Comment by clessig** [comment]
Yes, the limitation with that you have to have singleformers for the embedding nets is true. But you have these, not?

**Comment by ankitpatnala** [comment]
Yes! I have them but I want to make use of updated weights of multiformer, the same id will be used for updated weights of encoders and decoder modules too.

**Comment by clessig** [comment]
From the singleformer only the embedding net weights should be loaded so this shouldn't be an issue.

**Comment by iluise** [comment]
Hi, is the multiformer you are trying to load one of the old ones from the paper or the new ones I gave you a few weeks ago? Because in the second case it should work out of the box, I call `continue_training` with no problem and it uses the same functions. 

With the old runs is a bit more tricky as they were also trained with a different precision and no flash attention, right? Isn't maybe easier if you just pull an older version of the code, like tag v0.0?

**Comment by ankitpatnala** [comment]
I use the new one i.e. the second case. It works maybe for two reasons
-> In the json file, the model_ids are still from singleformers. 
-> Continue training, simple loads from the model and does not use this nlock of code.

**Comment by ankitpatnala** [comment]
```
   self.embeds_token_info = torch.nn.ModuleList()
    for ifield, field_info in enumerate( cf.fields) :
      
      self.embeds_token_info.append( torch.nn.Linear( cf.size_token_info, cf.size_token_info_net))
      
      if not load_pretrained :
          # initalization
          torch.nn.init.constant_( self.embeds_token_info[-1].weight, 0.0)
          self.embeds_token_info[-1].bias.data.fill_(0.0)

    if load_pretrained:
        name = 'AtmoRep' + '_embeds_token_info'
        if not os.path.exists(get_model_filename( name, cf.fields[0][1][4][0], cf.fields[0][1][4][1])):
            name = 'AtmoRep' + '_embed_token_info'

        mloaded = torch.load( get_model_filename( name, cf.fields[0][1][4][0], cf.fields[0][1][4][1]))
        self.embeds_token_info.load_state_dict( mloaded)
        print( 'Loaded embed_token_info from id = {}.'.format( cf.fields[0][1][4][0] ) )
```
I wrote this line of code to make it work for my current case. Later realized this would not work for singleformers case. All we can do is give a check number of key in the embeds_token_info module. If it is twice the number of fields, we can be certain this is the model_id of the multiformer.  and use fidx instead of 0 else when it is not multiformer, we can use 0 as it is currently now.
